name: PlayerDataPlugin
main: com.monkeygamesmc.plugin.playerdata.PlayerDataPlugin
version: 0.2
load: STARTUP
commands:
  showplayerdata:
    usage: /showplayerdata <player>
    permission: playerdata.showplayerdata
  setplayerdata:
    usage: /setplayerdata <player> <key> <data>
    permission: playerdata.setplayerdata